# Generated by Django 5.1 on 2024-08-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('date',), 'verbose_name': 'Kamp', 'verbose_name_plural': 'Kamper'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Kamptropp', 'verbose_name_plural': 'Kamptropp'},
        ),
        migrations.AlterModelOptions(
            name='squad',
            options={'ordering': ('shirt_no',), 'verbose_name': 'Spillerstall', 'verbose_name_plural': 'Spillere i stallen'},
        ),
        migrations.RemoveConstraint(
            model_name='squad',
            name='unique_name_shirtno',
        ),
    ]
