# Generated by Django 5.1.7 on 2025-03-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.match')),
            ],
            options={
                'unique_together': {('ip_address', 'match')},
            },
        ),
    ]
