# Generated by Django 5.1.7 on 2025-03-09 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_ip', models.CharField(max_length=64)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.match')),
            ],
            options={
                'unique_together': {('hashed_ip', 'match')},
            },
        ),
    ]
