# Generated by Django 5.1.7 on 2025-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_votelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
